sudo: false
language: node_js
node_js:
  - "6"

addons:
  apt:
    packages:
    - jq

install:
- npm install

script:
- bash ./bin/travis-script.sh

after_success:
- bash ./bin/travis-after-success.sh

branches:
  only:
  - master
  - rc.x
