sudo: false
language: ruby
rvm:
- 2.0.0
cache: bundler
script: bundle exec rake -t
after_success:
- bash ./.travis.after_success.sh
env:
  global:
    secure: VMTB+NAGPhANSwSxWZEONyOUB4V8iFicRehMy5rj4ytsZMkkmC4tL/bdzOqIc8oeu9RaNT+dbxeEauyTZts1YVg0Y1r+7L7KeHUMnLB4B4q/Q1Bp0pXfKzuMMq6hzCXQBkARQLwI5pXvp+WM9YG7MLROtAIMux4sFiRpN5eSc6CFwfe9+JbPcLqVbtgMPCcbpxPYyMVSJuSRkvpnO7vzBvp2DlOrFWBAIHa4SOjrMGRIhtqm7lPqGNY6A1kmru6xLeOHRZueuuC110Zxk9i025YWjVZvlgxizKOTmIFh/v1jUCAQiFGeKTdhOQEy0LKSe6M0q1t2ElJtoJm364WLpYICVw9Mz5CNSiqfDKFahjDdRYjYlB8sh3KwtAFi47WSaNaQJJscxsO2r28m2RmLBEyWWTno3tKtsPJc1yY3Xwm20RbihiyVFcUmWnkSV0bFFs3tgQOlD41SdCqviTvCGzLPcSazZN4vCvIIBQPnpxB12RJBp2gzPJkE7iEv/BobB9E7KsnEn5ESdmGuZJL9eO03am8StAU76ezN1pEkL0J55fIE19Kssa0vsR/ioklnMXQrShGnCc2KhAiYSoPciIX1AhPTF9hx9YpMbiAy5X+YRhWFUkTxWgTbi69h9vFbNcpbrSM5iqgbECZBpK1QFTcYEW7WFmw1PE8lczSgb7I=
