sudo: false
language: ruby
rvm:
- 2.0.0
cache: bundler
script: bundle exec rake -t
after_success:
  - chmod 755 ${TRAVIS_BUILD_DIR}/deploy.sh && sh -c "${TRAVIS_BUILD_DIR}/deploy.sh"
env:
  global:
    secure: lOgsUFCHFwuOlAB+WV/6KybnA5uXyxj5KASU0rjgOb/xZNfeWR/UPQYzNI0e3bmyBbGVGJvwIrDg2TBalq8Vl7pjxOwOSL7zVDwJSOLYz/TvCQMUL8gS6XZKuVD5YXjAJVCLZoaUq+TH+ZggtZ1vvUlgnp6M4Ii1QZ6tmLLAaM6APBzSHP59URJ454Adhq3QuWwS5knYftCYLjbZ2alnlPn+wDLaaLOO8sJIgyyOn3eSn5PTu9/ob/iVXy92KzlsiaYRaei2NJouqVLbiTgRUiQ3sv+zCC9auq73poWPRlf3ouII5splRDcr1SF1yKKR8ySRi86EI/WPyHaGamcNpUskmoO07ARyJ5XgrXX+2sfb3/6glyLSbWJRE82E58/mgoB1ZZJx3Qhx0bbwywnH/K2plTtqPOOodmPoRJO2dmS5bRXxN6lmwVDPaaCD9zsowh1MmlxEK16WlKov1EkMI/7J8fx43+YFST3ZvC14Tji3G9sH7Ecwm38eUvTGFJ/ptYOYCHru78g8Ro6fcbRLntn5MfaX5nJeaV425W3KF7HIhBnnV3yb1Nr1g4LRHQGJCzi5F9yhksRGxf6qU1atJAzewkTaZq+UbxcSnDF1Va/IQ6b/6ClefhCNAyK03ulSJ9IT4enLHcfEq4ykL8r5X3Z8fymj9fKfABeHReFE1Yg=
